# Reactive PostgreSQL datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=release_user
quarkus.datasource.password=release_pass
quarkus.datasource.reactive.url=postgresql://localhost:5432/release_pilot
# Hibernate Reactive
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=false
# RabbitMQ
rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=release_user
rabbitmq-password=release_pass