services:
  postgres:
    image: postgres:18-alpine
    container_name: release-pilot-postgres
    environment:
      POSTGRES_DB: release_pilot
      POSTGRES_USER: release_user
      POSTGRES_PASSWORD: release_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pilot

  rabbitmq:
    image: rabbitmq:4.2.8-alpine
    container_name: release-pilot-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: release_user
      RABBITMQ_DEFAULT_PASS: release_pass
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  app:
    build:
      context: ../../..
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: release-pilot-app
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: release_user
      QUARKUS_DATASOURCE_PASSWORD: release_pass
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://postgres:5432/release_pilot
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: release_user
      RABBITMQ_PASSWORD: release_pass

volumes:
  postgres_data:
  rabbitmq_data: